services:
  webapp:
    image: tomdeganck/webapp
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      - MYSQL_URL=mysql://root:rootpassword@database:3306/webapp_db
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  test:
    image: tomdeganck/webapp
    depends_on:
      - webapp
    environment:
      API_URL: http://webapp:3000
    command: yarn test

volumes:
  db_data:
